services:
  - docker

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed longtran020299/udagram-api-feed:v1
  - docker tag udagram-api-user longtran020299/udagram-api-user:v1
  - docker tag udagram-frontend longtran020299/udagram-frontend:v1
  - docker tag udagram-reverseproxy longtran020299/udagram-reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push longtran020299/udagram-api-feed:v1
  - docker push longtran020299/udagram-api-user:v1
  - docker push longtran020299/udagram-frontend:v1
  - docker push longtran020299/udagram-reverseproxy:v1
